# Generated by Django 3.2.3 on 2021-05-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='over_view',
            new_name='overview',
        ),
    ]
