# Generated by Django 3.2.3 on 2021-05-18 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210518_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
