# Generated by Django 3.2.3 on 2021-05-18 15:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default='testi'),
            preserve_default=False,
        ),
    ]
