# Generated by Django 3.2.3 on 2021-05-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
